apiVersion: apps/v1
kind: Deployment
metadata:
  name: ankyra
  labels:
    app: ankyra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ankyra
  template:
    metadata:
      labels:
        app: ankyra
    spec:
      containers:
        - name: ankyra
          image: docker.io/rmisiarek/ankyra:0.1
          ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ankyra
  labels:
    app: ankyra
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
  selector:
    app: ankyra
